### ISSUE TITLE
Release ?

### ISSUE THREAD

**Issue by hadim** [scijava/scijava-plugins-io-table#1]
I know you plan to migrate this component [elsewhere](https://github.com/scijava/scijava-common/issues/314). In the meantime, would you be ok to release a version of this so I can use it in my project waiting for the refactoring?

Thank you.

ping @stelfrich

**Comment by hadim** [comment]
[This issue](https://github.com/imagej/imagej-common/issues/75) is probably more relevant than this one.

**Comment by stelfrich** [comment]
@hadim: I could still cut a release if you want. I don't think that the migration is going to happen any time soon...

**Comment by hadim** [comment]
Ok, that would be nice. Thank you @stelfrich.

**Comment by stelfrich** [comment]
@hadim Sorry that I had forgotten to cut a release! There is one now of the migrated component, though...
