### ISSUE TITLE
Move this repository to scijava-plugins-io-table

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-plugins-io-table#2]
Let's move this repository to `scijava-plugins-io-table` (as suggested in https://github.com/scijava/scijava-common/issues/314#issuecomment-366215790 and mentioned in https://github.com/imagej/imagej-common/issues/75 and https://github.com/scijava/scijava-table/pull/2).

@stelfrich, @hadim are you ok if this simply gets _moved_ (and then the package names and references adjusted), instead of creating a new repository and copying the history (to keep this component around and deprecate it)?

**Comment by hadim** [comment]
Whatever is the most convenient for you. Thanks for working on this. I can take care of the UI part when you're done with io and table repo.

**Comment by stelfrich** [comment]
No hard feelings involved, just go ahead 👍

**Comment by imagejan** [comment]
I lack the permissions in the `imagej` org to be able to move this repository elsewhere. @stelfrich can you do it? I'll open a PR soon to adjust artifact name, package names, etc...

**Comment by stelfrich** [comment]
> I lack the permissions in the `imagej` org to be able to move this repository elsewhere. @stelfrich can you do it? I'll open a PR soon to adjust artifact name, package names, etc...

I was able to rename the repository, but cannot transfer ownership since I am not allow to create repositories in the `scijava` org. @ctrueden, could you please grant me those rights or transfer ownership of this repository to the `scijava` org (preferred)?

**Comment by imagejan** [comment]
> could you please grant me those rights

I was able to grant you those rights on the scijava organization, and just made you owner to permit creating new repositories.

**Comment by stelfrich** [comment]
> I was able to grant you those rights on the scijava organization, and just made you owner to permit creating new repositories.

Done!

**Comment by ctrueden** [comment]
Thanks, guys!
